/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Agent": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AgentEdge": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Badge": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Spa": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}